language: python
python:
  - "3.6"

before_install:
  - mkdir abidjan
  - git clone https://github.com/nlehuby/gpx_snippets

script:
  - python analyse_tracks.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  local_dir: abidjan
  keep-history: true
  on:
    branch: master
